version: '3.9'

services:
  snapshot-listener:
    image: proto-snapshot-listener
    expose:
      - 9100
      - 9988
    ports:
      - 9100:9100
      - 9988:9988
    volumes:
      - ./shared_volume:/keys
    environment:
      - PROTOCOL_STATE_CONTRACT=$PROTOCOL_STATE_CONTRACT
      - PROST_RPC_URL=$PROST_RPC_URL
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - RELAYER_RENDEZVOUS_POINT=$RELAYER_RENDEZVOUS_POINT
      - RELAYER_PRIVATE_KEY=$RELAYER_PRIVATE_KEY
      - AUTH_READ_TOKEN=$AUTH_READ_TOKEN
    command:
      bash -c  "sh listener_autofill.sh && sh init_processes.sh"